/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;
import java.sql.*;
import java.util.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class daftar extends javax.swing.JFrame {

    /**
     * Creates new form daftar
     */
    public daftar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_input_email = new javax.swing.JTextField();
        btn_daftar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_input_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_input_email.setBackground(new java.awt.Color(234, 234, 234));
        txt_input_email.setBorder(null);
        txt_input_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_input_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_input_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 290, 40));

        btn_daftar.setBackground(new java.awt.Color(67, 86, 108));
        btn_daftar.setForeground(new java.awt.Color(255, 255, 255));
        btn_daftar.setText("SIMPAN");
        btn_daftar.setToolTipText("");
        btn_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 250, 70));

        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, -1, -1));

        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));

        txt_input_password.setBackground(new java.awt.Color(234, 234, 234));
        txt_input_password.setBorder(null);
        txt_input_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_input_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_input_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 300, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_componen_asset/daftar1.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1430, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftarActionPerformed
        // Get user input
    String email = txt_input_email.getText();
    String password = new String(txt_input_password.getPassword());

    try {
        // Establish database connection
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/java_user_database", "root", "");
        Statement st = con.createStatement();

        // Check if the email already exists
        String checkEmailQuery = "SELECT * FROM user WHERE email='" + email + "'";
        ResultSet rs = st.executeQuery(checkEmailQuery);

        if (rs.next()) {
            JOptionPane.showMessageDialog(null, "Email already exists. Please choose a different email.");
        } else {
            // If the email is not in use, insert the new user
            String insertUserQuery = "INSERT INTO user (email, password) VALUES ('" + email + "', '" + password + "')";
            int rowsAffected = st.executeUpdate(insertUserQuery);

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Registration successful!");
                // Optionally, you can redirect to the login page after successful registration
                dispose(); // Close the current registration window
                new login().setVisible(true); // Open the login window
            } else {
                JOptionPane.showMessageDialog(null, "Registration failed. Please try again.");
            }
        }

        // Close resources
        rs.close();
        st.close();
        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error while establishing connection!!");
    }

    }//GEN-LAST:event_btn_daftarActionPerformed

    private void txt_input_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_input_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_input_emailActionPerformed

    private void txt_input_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_input_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_input_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new daftar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_daftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_input_email;
    private javax.swing.JPasswordField txt_input_password;
    // End of variables declaration//GEN-END:variables
}
