/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException; 
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class hotel extends javax.swing.JFrame {

    /**
     * Creates new form hotel
     */
    public hotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_email_hotel = new javax.swing.JTextField();
        txt_nama_hotel = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        btn_konsul = new javax.swing.JButton();
        btn_groom = new javax.swing.JButton();
        btn_pesan = new javax.swing.JButton();
        btn_shop1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        jLabel3.setText("Nama Pemilik");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        jLabel4.setText("Durasi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, -1, -1));

        txt_email_hotel.setBackground(new java.awt.Color(234, 234, 234));
        txt_email_hotel.setBorder(null);
        txt_email_hotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_email_hotelActionPerformed(evt);
            }
        });
        getContentPane().add(txt_email_hotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 290, 50));

        txt_nama_hotel.setBackground(new java.awt.Color(234, 234, 234));
        txt_nama_hotel.setBorder(null);
        txt_nama_hotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_hotelActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nama_hotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 290, 50));

        jTextField1.setBackground(new java.awt.Color(234, 234, 234));
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 280, 50));

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 130, 40));
        home.getAccessibleContext().setAccessibleDescription("");

        btn_konsul.setText("Konsultasi");
        btn_konsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_konsulActionPerformed(evt);
            }
        });
        getContentPane().add(btn_konsul, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 130, 40));

        btn_groom.setText("Grooming");
        btn_groom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_groomActionPerformed(evt);
            }
        });
        getContentPane().add(btn_groom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 130, 40));

        btn_pesan.setBackground(new java.awt.Color(109, 100, 100));
        btn_pesan.setForeground(new java.awt.Color(255, 255, 255));
        btn_pesan.setText("PESAN");
        btn_pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 640, 170, 70));

        btn_shop1.setText("Shop");
        btn_shop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_shop1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_shop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 130, 40));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Anjing");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Kucing");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_componen_asset/Hotel1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nama_hotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_hotelActionPerformed
        // TODO add your handling code here:
        dispose();
        new hotel().setVisible(true);
    }//GEN-LAST:event_txt_nama_hotelActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        dispose();
        new home().setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void btn_pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesanActionPerformed
        String email = txt_email_hotel.getText();
        String namaPemilik = txt_nama_hotel.getText();
        String durasi = jTextField1.getText();
        String jenisHewan = jRadioButton1.isSelected() ? "Anjing" : "Kucing";

        if (!isEmailExists(email)) {
            JOptionPane.showMessageDialog(this, "Email not registered. Please register first.");
            return;  // Stop further processing
        }
        // Insert data into the database
        try {
            // Establish database connection
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/java_user_database", "root", "");

            // Prepare SQL statement
            String sql = "INSERT INTO hewanhotel (email, nama_pemilik, durasi, nama_hewan) VALUES (?, ?, ?, ?)";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);

            // Set values for parameters
            preparedStatement.setString(1, email);
            preparedStatement.setString(2, namaPemilik);
            preparedStatement.setString(3, durasi);
            preparedStatement.setString(4, jenisHewan);

            // Execute the SQL statement
            preparedStatement.executeUpdate();

            // Close the resources
            preparedStatement.close();
            connection.close();

            // Show confirmation or redirect to the confirmation page
            dispose();
            new konfirmasiHotel().setVisible(true);

        } catch (SQLException e) {
            // Handle any SQL exceptions
            e.printStackTrace();
        }

        dispose();
        new konfirmasiHotel().setVisible(true);
    }//GEN-LAST:event_btn_pesanActionPerformed
        
         private boolean isEmailExists(String email) {
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/java_user_database", "root", "");
            String sql = "SELECT * FROM user WHERE email = ?";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, email);
            ResultSet resultSet = preparedStatement.executeQuery();

            boolean exists = resultSet.next();

            // Close the resources
            resultSet.close();
            preparedStatement.close();
            connection.close();

            return exists;
        } catch (SQLException e) {
            // Handle any SQL exceptions
            e.printStackTrace();
            return false;  // Assuming an error means the email doesn't exist
        }
    }

    private void btn_groomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_groomActionPerformed
        // TODO add your handling code here:
        dispose();
        new grooming().setVisible(true);
    }//GEN-LAST:event_btn_groomActionPerformed

    private void btn_konsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_konsulActionPerformed
        // TODO add your handling code here:
        dispose();
        new konsultasi().setVisible(true);
    }//GEN-LAST:event_btn_konsulActionPerformed

    private void btn_shop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_shop1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_shop1ActionPerformed

    private void txt_email_hotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_email_hotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_email_hotelActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_groom;
    private javax.swing.JButton btn_konsul;
    private javax.swing.JButton btn_pesan;
    private javax.swing.JButton btn_shop1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_email_hotel;
    private javax.swing.JTextField txt_nama_hotel;
    // End of variables declaration//GEN-END:variables
}
